development:
  adapter: postgresql
  database: angular_rails_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: angular_rails_development
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: angular_rails_development
  pool: 5
  timeout: 5000
